apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: spring-boot-api-applicationset
spec:
  generators:
    - list:
        elements:
          - cluster: dev-global-cluster-0
            url: https://kubernetes.default.svc
            profile: dev
          - cluster: prd-global-cluster-5
            url: https://kubernetes.default.svc
            profile: prd
  template:
    metadata:
      name: '{{name}}-{{profile}}'
    spec:
      project: '{{name}}-{{profile}}-project'
      source:
        repoURL: 'https://github.com/username/spring-boot-api'
        targetRevision: HEAD
        path: helm/spring-boot-api
        helm:
          valueFiles:
            - argocd/{profile}}/values.yaml
      destination:
        server: '{{url}}'
        namespace: '{{profile}}'
      syncPolicy:
        syncOptions:
       
