#Random secrets

apiVersion: v1
kind: Secret
metadata:
  name: spring-boot-api-secret
type: Opaque
data:
  apiKey: {{ .Values.secret.apiKey | b64enc | quote }}
  dbPassword: {{ .Values.secret.dbPassword | b64enc | quote }}
