# Expose app outside using clusterIP.

apiVersion: v1
kind: Service
metadata:
  name: spring-boot-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: spring-boot-api
  ports:
    - port: 8080
      targetPort: 8080
    - port: 8081
      targetPort: 8081
    - port: 8082
      targetPort: 8082
